# http_archive(
#     name = "build_bazel_rules_apple",
#     strip_prefix = "rules_apple-0.2.0",
#     urls = ["https://github.com/bazelbuild/rules_apple/archive/0.2.0.tar.gz"], # 2017-11-22
# )

# http_archive(
#     name = "io_bazel_rules_appengine",
#     sha256 = "d1fbc9a48332cc00b56d66751b5eb911ac9a88e820af7a2316a9b5ed4ee46d0b",
#     strip_prefix = "rules_appengine-0.0.7",
#     url = "https://github.com/bazelbuild/rules_appengine/archive/0.0.7.tar.gz",
# )

# #load("@io_bazel_rules_appengine//appengine:appengine.bzl", "appengine_repositories")

# #appengine_repositories()

# Servlet API 3.0 Reference implementation
http_jar(
    name = "javax_servlet_api",
    url = "https://bintray.com/artifact/download/bintray/jcenter/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar",
    sha256 = "af456b2dd41c4e82cf54f3e743bc678973d9fe35bd4d3071fa05c7e5333b8482",
)

bind(
    name = "javax/servlet/api",
    actual = "@javax_servlet_api//jar:jar",
)


# http_jar(
#     name = "lombok_jar",
#     url = "https://projectlombok.org/lombok-edge.jar",
# )

# http_jar(
#     name = "slf4j_jar",
#     url = "https://bintray.com/artifact/download/bintray/jcenter/org/slf4j/slf4j-api/1.7.9/slf4j-api-1.7.9.jar",
#     sha256 = "d6f79738bf5b6a7f8a51762dfc4e40754b721cd587a3e44b134351de5c8148da",
# )
